PREFIX ab: <http://learningsparql.com/ns/storebook#>
PREFIX d: <http://learningsparql.com/ns/data#>
#5 une requette qui permet de selectionner seulement les individus qui ont un nickame

##### comme on dit SELECT firstname, lastname,nick FROM table WHERE nick != null or exists
SELECT ?firstname ?lastname ?nick
WHERE{
	?s  ab:firstname ?firstname;
		ab:lastname ?lastname;
		ab:nick ?nick;
		EXISTS{
			?s ab:nick ?nick
		}
}

#4 une requette qui permet de selectionner seulement les individus qui ont worktel

SELECT ?firstname ?lastname
WHERE{
	?s ab:firstname ?firstname;
	   ab:lastname ?lastname
	EXISTS{
		?s ab:workTel ?workTel
	}
} 

#3 une requette qui permet de selectionner les individus qui nont pas worktel 

SELECT ?firstname ?lastname
WHERE{
	?s ab:firstname ?firstname ;
       ab:lastname ?lastname .
	  NOT EXISTS { ?s ab:workTel ?workTel }
}

# 2 une requette qui permet de selectionner firstname , lastname et nickame(sil existe) 

SELECT ?firstname ?lastname ?nickame
WHERE{
	?s  ab:firstname ?firstname ;
		ab:lastname ?lastname .
	OPTIONAL{
		?s ab:nick ?nickame
	}
}

#1 une requette qui permet de selectionner firstname , lastname et workTel(s''il exist) 

SELECT ?firstname ?lastname ?workTel
WHERE{
	?s  ab:firstname ?firstname ;
		ab:lastname ?lastname .
	OPTIONAL{
		?s ab:workTel ?workTel
	}
}

